run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - typecheck
    - gosec
    - bodyclose
    - errname
    - errorlint
    - gocyclo
    - unparam
    - noctx

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
  gosec:
    excludes:
      - G115 # integer overflow conversion (common with AWS SDK int32 conversions)
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
